#!/usr/bin/env node
// const { exec, execSync } = require('child_process');
const util = require('util');
const execFile = util.promisify(require('child_process').execFile);

process.stdin.write('Working with execFile \n');

async function getVersion() {
	const { stdout } = await execFile('node', ['--version']);
	console.log(stdout);
}
getVersion();
