#!/usr/bin / env node
const { spawn } = require('child_process');

process.stdin.write('Hello, World\n');

const ls = spawn('ls', ['-lh', '.']);

ls.stdout.on('data', data => {
	console.log(`stdout: ${data}`);
});

ls.stderr.on('data', data => {
	console.error(`stderr: ${data}`);
});

ls.on('close', code => {
	console.log(`child process exited with code ${code}`);
});

// process.exit(0);
